# Generated by Django 5.0.4 on 2024-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction_related_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='related_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
